# Generated by Django 4.2.7 on 2023-12-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0002_leavetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='leave_type',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
