# Generated by Django 4.2.7 on 2023-12-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0004_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
